-- 코드를 입력하세요
SELECT *
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE IN ('세단', 'SUV');

-- 자동차 종류가 '세단' 또는 'SUV'인 자동차 중 2022-11-01부터 2022-11-30까지 대여 가능하고 30일간 대여금액이
-- 50만원 이상 200만원 미만인 자동차에 대해서 자동차 ID, 종류, 대여금액리스트를 출력하는 SQL문 작성
SELECT *
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE < '2022-12-01' AND END_DATE > '2022-11-01';



SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_ID NOT IN(                          -- 대여 가능한 세단, SUV 목록
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE < '2022-12-01' AND END_DATE >= '2022-11-01'
)
AND C.CAR_TYPE IN ('세단', 'SUV')
AND D.duration_type = '30일 이상'
GROUP BY C.CAR_ID
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;